 //account Info
 export const GET_ACCOUNT_INFO_REQUEST = "GET_ACCOUNT_INFO_REQUEST";
 export const GET_ACCOUNT_INFO_SUCCESS = "GET_ACCOUNT_INFO_SUCCESS";
 export const GET_ACCOUNT_INFO_ERROR = "GET_ACCOUNT_INFO_ERROR";

 export const GET_COLLECTION_REQUEST = "GET_COLLECTION_REQUEST";
 export const GET_COLLECTION_SUCCESS = "GET_COLLECTION_SUCCESS";
 export const GET_COLLECTION_ERROR = "GET_COLLECTION_ERROR";

 export const GET_REQUEST = "GET_REQUEST";
 export const GET_SUCCESS = "GET_SUCCESS";
 export const GET_ERROR = "GET_ERROR";